#440 Reproducibility and Statistics Assignment Homework

<!-- This is an Rmd comment. -->
<!--
You can make comments several lines long by inserting
the text in between the the start and the end of the 
comment.

Comments are where I'll tell you what to do. You should
use the space directly below the comments to do what
the comment asks. You should also describe what you're
doing to make it obvious to the reader so they can
easily follow your logic in a fully reproducible way.
For any statistical tests you run, you should explain
the results in plain English and present the statistics
as you would in an APA style manuscript. For any symbols
you don't know how to use/can't use, feel free to use the name
instead (e.g. alpha)
--> 

<!-- Load the politics.csv data file. -->

politics<-read.csv("politics.csv")
#This loads the politics file and attaches the name politics to the data

<!-- 
Check the structure.
subject, party, testtime, minwage, and sex need to be factors.
optimismscore and income should be integer and numeric vectors.
Fix any variables that aren't right.
-->

str(politics)
#This explains the structure and variables of the data (subject, party, testtime, optimismscore, minwage, sex, and income)

<!-- Find the minimum, mean, and variance for posttest
optimism scores. -->

summary(politics$optimismscore[politics$testtime=="post"])
#This command gives us the minimum, 1st Quartile, mean, 3rd Quartile and the maximum.  The bracketed information asks for the optimism score for the post testtime.

var(politics$optimismscore[politics$testtime=="post"])
#This give sus the variance, again for posttest optimism scores

<!-- Create a histogram of posttest optimism scores.
Feel free to use the default ugly settings since
we didn't cover how to do this in ggplot2. If
you're a real go-getter, see if you can figure
out how to make a prettier histogram with better
labels, etc. using ggplot2. -->

hist(politics$optimismscore[politics$testtime=="post"])
#We have a histogram for posttest optimism scores!  


<!-- Run a test to determine whether political affiliation
is independent of one's gender.
Present the data supporting your analyses in graphical or
tabular form.
-->

#In order to determine if two variables are independent of each other, I use the Chi-square test.  

post<-politics$testtime=="post"
#The data is presented twice, so this divides and creats a shortened notation for the posttest data.

chisq.test(politics$party[post],politics$sex[post])
#This is the chi-squared test.  X-squared = 0.72674, df = 2, p-value = 0.6953

pre<-politics$testtime=="pre"
chisq.test(politics$party[pre], politics$sex[pre])
#I wanted to double check that the pre and post testscores elicited the same data, so I ran the chi-squared test for pretest scores also and got the same values. Yay!
#This data shows that sex and party are independent of one another. 

<!-- Run a test to determine whether or not males and females
have different incomes.
Create a graph to display your data that includes the relevant
means and standard errors.-->

#In order to determine if males and femals have differing incomes, we need to conduct an independent t-test.  

t.test(politics$income[politics$testtime=="post" & politics$sex=="male"],politics$income[politics$testtime=="post" & politics$sex=="female"])

t = -1.5714, df = 61.623, p-value = 0.1212
mean of x = 38.80751
mean of y = 47.27310

#To graph this information I will use dplyr and ggplot2, which I get ready by the following commands

library ("dplyr")
library ("ggplot2")
#I designated the data I wanted to group and use as polsum, which was sex and income
polsum<-politics%>%group_by(sex)%>%summarize(mean=mean(income),sems=sd(income)/sqrt(length(income)))

polsum

#To make the figure I used ggplot, assigned the polsum data and then designated x as sex and y as the means.  I then set the outline as black and the fill as green and pink. Finally, I ran the figure!
fig<-ggplot(polsum,aes(x=factor(sex),y=mean))

fig<-fig+ geom_bar(stat="identity", color="black", fill=c("deeppink","darkgreen")) 

fig<-fig+geom_errorbar(aes(ymax=mean+sems, ymin=mean-sems),width=.2)

fig

<!-- See if male and females with different political affiliations
have different posttest optimism scores. Create a graph to display
your data that includes the relevant means and standard errors.-->
#The following is the command for a two-way between-subjects ANOVA

summary(aov(optimismscore~party*sex,data=politics[politics$testtime=="post",]))


            Df Sum Sq Mean Sq F value  Pr(>F)    
party        2  10147    5074  27.063 4.2e-09 ***
sex          1      7       7   0.040   0.843    
party:sex    2    455     227   1.213   0.304    
Residuals   60  11248     187                    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

#These data show that optimism scores are associated with party affiliation.  Sex is not associated with optimism scores.  There was no interaction of party and sex.  

<!-- Create a line graph for the same data. With
error bars of course!-->

opto<-politics[politics$testtime=="post",]%>%group_by(party,sex)%>%summarize(mean=mean(optimismscore),sems=sd(optimismscore)/sqrt(length(optimismscore)))
library("ggplot2")
library("dplyr")
col1=("deeppink")
col2=("deepskyblue2")
fig1<-ggplot(opto,aes(x=party, y=mean, group=sex, colour=sex))+
geom_line(size=1)+
geom_point(size=2) +
scale_color_manual(values=c(col1,col2),name="Sex",breaks=c("female","male"),labels=c("Female", "Male"))+
geom_errorbar(aes(ymax=mean+sems, ymin=mean-sems),width=.2)+
ggtitle("Optimism Score by Sex and Political Affiliation")+
labs(x="Political Party Affiliation",y="optimismScore")+
scale_x_discrete(breaks=c("democrat","independent","republican"),labels=c("Democrat","Independent","Republican"))+
theme(plot.title=element_text(size=15,face="bold",vjust=.5))+
theme(axis.title.x=element_text(size=12,face="bold",vjust=-.25))+
theme(axis.title.y=element_text(size=12,face="bold",vjust=1))+
theme(axis.text.x=element_text(size=10,face="bold",color="black"))+
theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
coord_cartesian(ylim=c(min(opto$mean)-2*max(opto$sems),+
max(opto$mean)+2*max(opto$sems)))+
theme(panel.border=element_blank(),axis.line=element_line())+
theme(panel.grid.major.x=element_blank())+
theme(panel.grid.major.y=element_line(color="darkgrey"))+
theme(panel.grid.minor.y=element_blank())+
theme(legend.position=c(.2,.76))+
theme(legend.background=element_blank())+
theme(legend.background=element_rect(color="black"))+
theme(legend.title=element_blank())+
theme(legend.title=element_text(size=12))+
theme(legend.title.align=.5)+
theme(legend.text=element_text(size=10,face="bold"))

fig1

<!-- Run a test to see if optimism scores pre- and post
watching videos depends on sex.-->
#The following is a within subjects ANOVA test
summary(aov(optimismscore~testtime*sex+Error(subject/testtime),data=politics))

Error: subject
    Df Sum Sq Mean Sq
sex  1   18.5    18.5

Error: subject:testtime
         Df Sum Sq Mean Sq
testtime  1  622.3   622.3

Error: Within
              Df Sum Sq Mean Sq F value Pr(>F)
testtime       1    151   151.3   0.430  0.513
sex            1     66    66.4   0.189  0.664
testtime:sex   1      2     2.0   0.006  0.940
Residuals    126  44291   351.5   

# According to this data, pre and post videos did not depend on sex

<!-- Run a Multiple Regression Analysis to see
whether you can predict someones posttest optimism
scores from their pretest optimism scores and party
affiliation. Create a figure that shows the distributions
of pre- and posttest optimism scores and sex and create
lines that best fit the data for both sexes regardless of
whether the lines are warranted based on the statistical
analyses--> 

#The following is for the multiple regression analysis
summary(lm(optimismscore~income+sex,data=politics[politics$testtime=="post",]))
#I made sure the plot packages were available in the library
library("ggplot2")
library("dplyr")

#This command abbreviated posttest as pres, and the next designated the specifics for a scatter plot and regression lines.
pres<-politics[politics$testtime=="post",]
fig2<-ggplot(pres,aes(x=income,y=optimismscore,color=sex))+
geom_point(size=2)+
geom_abline(intercept=60.2+2.51/2, slope=-.092,color=col1)+
geom_abline(intercept=60.2-2.51/2, slope=-.092,color=col2)+
scale_color_manual(values=c(col1,col2),breaks=c("female","male"),
labels=c("Female","Male"))+
ggtitle("Optimism Predicted by Sex and Income")+
labs(x="Income (Thousands of Dollars)",y="Optimism Score\n(Higher=More)")+
theme(plot.title=element_text(size=15,face="bold", vjust=.5))+
theme(axis.title.x=element_text(size=12,face="bold", vjust=-.25))+
theme(axis.title.y=element_text(size=12,face="bold", vjust=1))+
theme(axis.text.x=element_text(size=10,face="bold",color="black"))+
theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
theme(panel.border=element_blank(), axis.line=element_line())+
theme(panel.grid.major.x=element_blank())+
theme(panel.grid.minor.x=element_blank())+
theme(panel.grid.major.y=element_line(color="darkgrey"))+
theme(panel.grid.minor.y=element_blank())+
theme(legend.position=c(.83,.86))+
theme(legend.background=element_blank())+
theme(legend.title=element_blank())+
theme(legend.text=element_text(size=10,face="bold"))
fig2

